site_name: Documentaci√≥n Yeray Gutierrez Mullor
site_url: https://github.com/yerayyeray/mkdocs.git
docs_dir: docs
site_dir: site

nav:
  - Inicio: index.md
  - Minima: Ejercicio1.md
  - Lagrange: Ejercicio2.md
  - YAT: Ejercicio3.md
theme: readthedocs